name: quickstart
version: '1.3.3'
summary: Raspberry PI 3 simple control service
description: |
  Runs a recurrent sensors reads and saves data to a storage

confinement: devmode
grade: devel
base: core18
architectures: [armhf]

parts:
  quickstart:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python3
      - python3-dev
      - libmysqlclient-dev
      - build-essential 
      - libssl-dev 
      - libffi-dev

apps:
  quickstart:
    command: bin/writetest.py
    daemon: simple
    restart-condition: always
  quicksynch:
    command: bin/synchronize.py
    daemon: simple
    restart-condition: always
